[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true

[rpc_endpoints]
NOLLIE_RPC = "https://nollie-rpc.skatechain.org"
AMOY_RPC = "https://rpc-amoy.polygon.technology"
BASE_RPC = "https://base-sepolia-rpc.publicnode.com"
ARB_RPC = "https://endpoints.omniatech.io/v1/arbitrum/sepolia/public"
BSC_RPC = "https://data-seed-prebsc-2-s3.bnbchain.org:8545"
OP_RPC = "https://optimism-goerli.public.blastapi.io"


[fmt]
line_length = 80
int_types = "long"
bracket_spacing = true
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "single"
single_line_statement_blocks = "single"
fs_permissions = [{ access = "read", path = "./" }]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
